name: JavaScript Action
author: Austen Stone
description: A JavaScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

runs:
  using: "node16"
  main: "dist/index.mjs"
